# Review of Linear Algebra Basics
To use quantum mechanics, you should be familiar with linear algebra operations. The following exercises help you to review some basic operations with vectors and matrices.

:::{admonition} Exercise 1
:class: exercise

 Calculate the vector product $\mathbf{c}=\mathbf{a}\times\mathbf{b}$
    with 

   $$
    \begin{aligned}
     \mathbf{a} = \left(\begin{matrix}
     2 \\ 6 \\ 4
     \end{matrix}\right)
     \quad
     \mathbf{b} = \left(\begin{matrix}
     5 \\ 1 \\ 7
     \end{matrix}\right)
     \end{aligned}
    $$

  and, for the same $\mathbf{a},\mathbf{b}$, the scalar product
    
   $$
    \begin{aligned}
     d = \mathbf{a}\cdot \mathbf{b}
     \end{aligned}
   $$
:::

In [3]:
import numpy as np

a = np.array([2, 6, 4])
b = np.array([5, 1, 7])
np.cross(a, b)

array([ 38,   6, -28])

:::{admonition} Exercise 2
:class: exercise
 Evaluate the matrix product $\mathbf{C} = \mathbf{A}\mathbf{B}$.

   $$
    \mathbf{A} =\begin{aligned}
     \left(\begin{matrix}
     6 & 8 &2 \\ 9 & 1 & 5 \\ 7 & 4 & 3
     \end{matrix}\right),\quad\mathbf{B}=
      \left(\begin{matrix}
     9 & 6 & 7 \\ 5 & 4 & 4 \\  3 & 2 & 8
     \end{matrix}\right).
     \end{aligned}
    $$

:::

In [2]:

A = np.array([[6, 8, 2],
              [9, 1, 5],
              [7, 4, 3]])

B = np.array([[9, 6, 7],
              [5, 4, 4],
              [3, 2, 8]])

C = np.dot(A, B)
print(C)

[[100  72  90]
 [101  68 107]
 [ 92  64  89]]


:::{admonition} Exercise 3
:class: exercise
Evaluate the determinant for the matrix $\mathbf{A}$.
    
 $$
    \mathbf{A}=\begin{aligned}
     \left(\begin{matrix}
     1 & 1 & 2 \\ 1 & 0 & 2 \\ 2 & 2 & 3
     \end{matrix}\right)
     \end{aligned}
 $$

:::

In [5]:
A = np.array([[1, 1, 2],
              [1, 0, 2],
              [2, 2, 3]])

np.linalg.det(A)

np.float64(1.0)

:::{admonition} Exercise 4
:class: exercise
 Does the exponent of an operator always satisfy the relation
    $e^{\hat{A}+\hat{B}} = e^{\hat{A}}e^{\hat{B}}$ ? Start from the
    definition of the matrix exponential.
:::